### ISSUE TITLE
Unable to create secret for linked hero's quest

### ISSUE THREAD

**Issue by kabili207** [kabili207/oracle-hack#4]
There is currently no way to create secrets for a continuation of a Hero's Quest. Consider changing "Game Type" radio buttons into checkboxes.

**Comment by LunarCookies** [comment]
You could put 2 sets of 2 radio buttons
 - Normal/Hero game
 - New/Linked game

You can start a normal game using a code (strange heh)

**Comment by kabili207** [comment]
I can't believe the game actually lets you start a new normal game. I'd have thought Capcom would have checked for that kind of thing. It certainly has it's uses though.

Fixed with b77891d4f01995ed4e83b0c4e41498943db827b5 and kabili207/oracle-hack-win@f28c74bb56c40f8d447ac2eb4f37edf38d0433ab.
